name: grocery
description: "A new Flutter project."

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.0
  form_field_validator: ^1.1.0
  animations: ^2.0.11
  flutter_credit_card: ^3.0.3
  carousel_slider: ^5.0.0
  # HTTP and state management packages
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  video_player: ^2.8.6
  chewie: ^1.5.0
  url_launcher: ^6.2.4
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo_splash.png"
  android: true
  ios: true
  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"


flutter:

  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
